openapi: 3.0.0

info:
  title: ドキュメントですよ
  version: 1.0.0

servers:
  - url: http://localhost:8000/

tags:
  - name: Mylibrary

paths:
  /mylibrary/books:
    $ref: './resources/mylibrary.yaml#/MylibraryBookPath'
  /mylibrary/books/{id}:
    $ref: './resources/mylibrary.yaml#/MylibraryBookWithIDPath'

components:
  schemas:
    Book:
      $ref: './schemas/book_schema.yaml'
  # securitySchemes:
  #   BearerAuth:
  #     $ref: './schemas/security_schema.yaml'